// file is auto generated by running yarn update-item-data
//prettier-ignore
const itemData = [
  {
    'cardId': 1,
    'path': 'items/gloomhaven/1-14/gh-001-boots-of-striding.png'
  },
  {
    'cardId': 2,
    'path': 'items/gloomhaven/1-14/gh-002-winged-shoes.png'
  },
  {
    'cardId': 3,
    'path': 'items/gloomhaven/1-14/gh-003-hide-armor.png'
  },
  {
    'cardId': 4,
    'path': 'items/gloomhaven/1-14/gh-004-leather-armor.png'
  },
  {
    'cardId': 5,
    'path': 'items/gloomhaven/1-14/gh-005-cloak-of-invisibility.png'
  },
  {
    'cardId': 6,
    'path': 'items/gloomhaven/1-14/gh-006-eagle-eye-goggles.png'
  },
  {
    'cardId': 7,
    'path': 'items/gloomhaven/1-14/gh-007-iron-helmet.png'
  },
  {
    'cardId': 8,
    'path': 'items/gloomhaven/1-14/gh-008-heater-shield.png'
  },
  {
    'cardId': 9,
    'path': 'items/gloomhaven/1-14/gh-009-piercing-bow.png'
  },
  {
    'cardId': 10,
    'path': 'items/gloomhaven/1-14/gh-010-war-hammer.png'
  },
  {
    'cardId': 11,
    'path': 'items/gloomhaven/1-14/gh-011-poison-dagger.png'
  },
  {
    'cardId': 12,
    'path': 'items/gloomhaven/1-14/gh-012-minor-healing-potion.png'
  },
  {
    'cardId': 13,
    'path': 'items/gloomhaven/1-14/gh-013-minor-stamina-potion.png'
  },
  {
    'cardId': 14,
    'path': 'items/gloomhaven/1-14/gh-014-minor-power-potion.png'
  },
  {
    'cardId': 15,
    'path': 'items/gloomhaven/15-21/gh-015-boots-of-speed.png'
  },
  {
    'cardId': 16,
    'path': 'items/gloomhaven/15-21/gh-016-cloak-of-pockets.png'
  },
  {
    'cardId': 17,
    'path': 'items/gloomhaven/15-21/gh-017-empowering-talisman.png'
  },
  {
    'cardId': 18,
    'path': 'items/gloomhaven/15-21/gh-018-battle-axe.png'
  },
  {
    'cardId': 19,
    'path': 'items/gloomhaven/15-21/gh-019-weighted-net.png'
  },
  {
    'cardId': 20,
    'path': 'items/gloomhaven/15-21/gh-020-minor-mana-potion.png'
  },
  {
    'cardId': 21,
    'path': 'items/gloomhaven/15-21/gh-021-stun-powder.png'
  },
  {
    'cardId': 22,
    'path': 'items/gloomhaven/22-28/gh-022-heavy-greaves.png'
  },
  {
    'cardId': 23,
    'path': 'items/gloomhaven/22-28/gh-023-chainmail.png'
  },
  {
    'cardId': 24,
    'path': 'items/gloomhaven/22-28/gh-024-amulet-of-life.png'
  },
  {
    'cardId': 25,
    'path': 'items/gloomhaven/22-28/gh-025-jagged-sword.png'
  },
  {
    'cardId': 26,
    'path': 'items/gloomhaven/22-28/gh-026-long-spear.png'
  },
  {
    'cardId': 27,
    'path': 'items/gloomhaven/22-28/gh-027-major-healing-potion.png'
  },
  {
    'cardId': 28,
    'path': 'items/gloomhaven/22-28/gh-028-moon-earring.png'
  },
  {
    'cardId': 29,
    'path': 'items/gloomhaven/29-35/gh-029-comfortable-shoes.png'
  },
  {
    'cardId': 30,
    'path': 'items/gloomhaven/29-35/gh-030-studded-leather.png'
  },
  {
    'cardId': 31,
    'path': 'items/gloomhaven/29-35/gh-031-hawk-helm.png'
  },
  {
    'cardId': 32,
    'path': 'items/gloomhaven/29-35/gh-032-tower-shield.png'
  },
  {
    'cardId': 33,
    'path': 'items/gloomhaven/29-35/gh-033-volatile-bomb.png'
  },
  {
    'cardId': 34,
    'path': 'items/gloomhaven/29-35/gh-034-major-stamina-potion.png'
  },
  {
    'cardId': 35,
    'path': 'items/gloomhaven/29-35/gh-035-falcon-figurine.png'
  },
  {
    'cardId': 36,
    'path': 'items/gloomhaven/36-42/gh-036-boots-of-dashing.png'
  },
  {
    'cardId': 37,
    'path': 'items/gloomhaven/36-42/gh-037-robes-of-evocation.png'
  },
  {
    'cardId': 38,
    'path': 'items/gloomhaven/36-42/gh-038-heavy-basinet.png'
  },
  {
    'cardId': 39,
    'path': 'items/gloomhaven/36-42/gh-039-hooked-chain.png'
  },
  {
    'cardId': 40,
    'path': 'items/gloomhaven/36-42/gh-040-versatile-dagger.png'
  },
  {
    'cardId': 41,
    'path': 'items/gloomhaven/36-42/gh-041-major-power-potion.png'
  },
  {
    'cardId': 42,
    'path': 'items/gloomhaven/36-42/gh-042-ring-of-haste.png'
  },
  {
    'cardId': 43,
    'path': 'items/gloomhaven/43-49/gh-043-boots-of-quickness.png'
  },
  {
    'cardId': 44,
    'path': 'items/gloomhaven/43-49/gh-044-splintmail.png'
  },
  {
    'cardId': 45,
    'path': 'items/gloomhaven/43-49/gh-045-pendant-of-dark-pacts.png'
  },
  {
    'cardId': 46,
    'path': 'items/gloomhaven/43-49/gh-046-spiked-shield.png'
  },
  {
    'cardId': 47,
    'path': 'items/gloomhaven/43-49/gh-047-reaping-scythe.png'
  },
  {
    'cardId': 48,
    'path': 'items/gloomhaven/43-49/gh-048-major-mana-potion.png'
  },
  {
    'cardId': 49,
    'path': 'items/gloomhaven/43-49/gh-049-sun-earring.png'
  },
  {
    'cardId': 50,
    'path': 'items/gloomhaven/50-56/gh-050-steel-sabatons.png'
  },
  {
    'cardId': 51,
    'path': 'items/gloomhaven/50-56/gh-051-shadow-armor.png'
  },
  {
    'cardId': 52,
    'path': 'items/gloomhaven/50-56/gh-052-protective-charm.png'
  },
  {
    'cardId': 53,
    'path': 'items/gloomhaven/50-56/gh-053-black-knife.png'
  },
  {
    'cardId': 54,
    'path': 'items/gloomhaven/50-56/gh-054-staff-of-eminence.png'
  },
  {
    'cardId': 55,
    'path': 'items/gloomhaven/50-56/gh-055-super-healing-potion.png'
  },
  {
    'cardId': 56,
    'path': 'items/gloomhaven/50-56/gh-056-ring-of-brutality.png'
  },
  {
    'cardId': 57,
    'path': 'items/gloomhaven/57-63/gh-057-serene-sandals.png'
  },
  {
    'cardId': 58,
    'path': 'items/gloomhaven/57-63/gh-058-cloak-of-phasing.png'
  },
  {
    'cardId': 59,
    'path': 'items/gloomhaven/57-63/gh-059-telescopic-lens.png'
  },
  {
    'cardId': 60,
    'path': 'items/gloomhaven/57-63/gh-060-unstable-explosives.png'
  },
  {
    'cardId': 61,
    'path': 'items/gloomhaven/57-63/gh-061-wall-shield.png'
  },
  {
    'cardId': 62,
    'path': 'items/gloomhaven/57-63/gh-062-doom-powder.png'
  },
  {
    'cardId': 63,
    'path': 'items/gloomhaven/57-63/gh-063-lucky-eye.png'
  },
  {
    'cardId': 64,
    'path': 'items/gloomhaven/64-151/gh-064-boots-of-sprinting.png'
  },
  {
    'cardId': 65,
    'path': 'items/gloomhaven/64-151/gh-065-platemail.png'
  },
  {
    'cardId': 66,
    'path': 'items/gloomhaven/64-151/gh-066-mask-of-terror.png'
  },
  {
    'cardId': 67,
    'path': 'items/gloomhaven/64-151/gh-067-balanced-blade.png'
  },
  {
    'cardId': 68,
    'path': 'items/gloomhaven/64-151/gh-068-halberd.png'
  },
  {
    'cardId': 69,
    'path': 'items/gloomhaven/64-151/gh-069-star-earring.png'
  },
  {
    'cardId': 70,
    'path': 'items/gloomhaven/64-151/gh-070-second-chance-ring.png'
  },
  {
    'cardId': 71,
    'path': 'items/gloomhaven/64-151/gh-071b-boots-of-levitation.png'
  },
  {
    'cardId': 72,
    'path': 'items/gloomhaven/64-151/gh-072b-shoes-of-happiness.png'
  },
  {
    'cardId': 73,
    'path': 'items/gloomhaven/64-151/gh-073b-blinking-cape.png'
  },
  {
    'cardId': 74,
    'path': 'items/gloomhaven/64-151/gh-074b-swordedge-armor.png'
  },
  {
    'cardId': 75,
    'path': 'items/gloomhaven/64-151/gh-075b-circlet-of-elements.png'
  },
  {
    'cardId': 76,
    'path': 'items/gloomhaven/64-151/gh-076b-chain-hood.png'
  },
  {
    'cardId': 77,
    'path': 'items/gloomhaven/64-151/gh-077b-frigid-blade.png'
  },
  {
    'cardId': 78,
    'path': 'items/gloomhaven/64-151/gh-078b-storm-blade.png'
  },
  {
    'cardId': 79,
    'path': 'items/gloomhaven/64-151/gh-079b-inferno-blade.png'
  },
  {
    'cardId': 80,
    'path': 'items/gloomhaven/64-151/gh-080b-tremor-blade.png'
  },
  {
    'cardId': 81,
    'path': 'items/gloomhaven/64-151/gh-081b-brilliant-blade.png'
  },
  {
    'cardId': 82,
    'path': 'items/gloomhaven/64-151/gh-082b-night-blade.png'
  },
  {
    'cardId': 83,
    'path': 'items/gloomhaven/64-151/gh-083b-wand-of-frost.png'
  },
  {
    'cardId': 84,
    'path': 'items/gloomhaven/64-151/gh-084b-wand-of-storms.png'
  },
  {
    'cardId': 85,
    'path': 'items/gloomhaven/64-151/gh-085b-wand-of-infernos.png'
  },
  {
    'cardId': 86,
    'path': 'items/gloomhaven/64-151/gh-086b-wand-of-tremors.png'
  },
  {
    'cardId': 87,
    'path': 'items/gloomhaven/64-151/gh-087b-wand-of-brilliance.png'
  },
  {
    'cardId': 88,
    'path': 'items/gloomhaven/64-151/gh-088b-wand-of-darkness.png'
  },
  {
    'cardId': 89,
    'path': 'items/gloomhaven/64-151/gh-089b-minor-cure-potion.png'
  },
  {
    'cardId': 90,
    'path': 'items/gloomhaven/64-151/gh-090b-major-cure-potion.png'
  },
  {
    'cardId': 91,
    'path': 'items/gloomhaven/64-151/gh-091b-steel-ring.png'
  },
  {
    'cardId': 92,
    'path': 'items/gloomhaven/64-151/gh-092b-dampening-ring.png'
  },
  {
    'cardId': 93,
    'path': 'items/gloomhaven/64-151/gh-093b-scroll-of-power.png'
  },
  {
    'cardId': 94,
    'path': 'items/gloomhaven/64-151/gh-094b-scroll-of-healing.png'
  },
  {
    'cardId': 95,
    'path': 'items/gloomhaven/64-151/gh-095b-scroll-of-stamina.png'
  },
  {
    'cardId': 96,
    'path': 'items/gloomhaven/64-151/gh-096-rocket-boots.png'
  },
  {
    'cardId': 97,
    'path': 'items/gloomhaven/64-151/gh-097-endurance-footwraps.png'
  },
  {
    'cardId': 98,
    'path': 'items/gloomhaven/64-151/gh-098-drakescale-boots.png'
  },
  {
    'cardId': 99,
    'path': 'items/gloomhaven/64-151/gh-099-magma-waders.png'
  },
  {
    'cardId': 100,
    'path': 'items/gloomhaven/64-151/gh-100-robes-of-summoning.png'
  },
  {
    'cardId': 101,
    'path': 'items/gloomhaven/64-151/gh-101-second-skin.png'
  },
  {
    'cardId': 102,
    'path': 'items/gloomhaven/64-151/gh-102-sacrificial-robes.png'
  },
  {
    'cardId': 103,
    'path': 'items/gloomhaven/64-151/gh-103-drakescale-armor.png'
  },
  {
    'cardId': 104,
    'path': 'items/gloomhaven/64-151/gh-104-steam-armor.png'
  },
  {
    'cardId': 105,
    'path': 'items/gloomhaven/64-151/gh-105-flea-bitten-shawl.png'
  },
  {
    'cardId': 106,
    'path': 'items/gloomhaven/64-151/gh-106-necklace-of-teeth.png'
  },
  {
    'cardId': 107,
    'path': 'items/gloomhaven/64-151/gh-107-horned-helm.png'
  },
  {
    'cardId': 108,
    'path': 'items/gloomhaven/64-151/gh-108-drakescale-helm.png'
  },
  {
    'cardId': 109,
    'path': 'items/gloomhaven/64-151/gh-109-thiefs-hood.png'
  },
  {
    'cardId': 110,
    'path': 'items/gloomhaven/64-151/gh-110-helm-of-the-mountain.png'
  },
  {
    'cardId': 111,
    'path': 'items/gloomhaven/64-151/gh-111-wave-crest.png'
  },
  {
    'cardId': 112,
    'path': 'items/gloomhaven/64-151/gh-112-ancient-drill.png'
  },
  {
    'cardId': 113,
    'path': 'items/gloomhaven/64-151/gh-113-skullbane-axe.png'
  },
  {
    'cardId': 114,
    'path': 'items/gloomhaven/64-151/gh-114-staff-of-xorn.png'
  },
  {
    'cardId': 115,
    'path': 'items/gloomhaven/64-151/gh-115-mountain-hammer.png'
  },
  {
    'cardId': 116,
    'path': 'items/gloomhaven/64-151/gh-116-fueled-falchion.png'
  },
  {
    'cardId': 117,
    'path': 'items/gloomhaven/64-151/gh-117-bloody-axe.png'
  },
  {
    'cardId': 118,
    'path': 'items/gloomhaven/64-151/gh-118-staff-of-elements.png'
  },
  {
    'cardId': 119,
    'path': 'items/gloomhaven/64-151/gh-119-skull-of-hatred.png'
  },
  {
    'cardId': 120,
    'path': 'items/gloomhaven/64-151/gh-120-staff-of-summoning.png'
  },
  {
    'cardId': 121,
    'path': 'items/gloomhaven/64-151/gh-121-orb-of-dawn.png'
  },
  {
    'cardId': 122,
    'path': 'items/gloomhaven/64-151/gh-122-orb-of-twilight.png'
  },
  {
    'cardId': 123,
    'path': 'items/gloomhaven/64-151/gh-123-ring-of-skulls.png'
  },
  {
    'cardId': 124,
    'path': 'items/gloomhaven/64-151/gh-124-doomed-compass.png'
  },
  {
    'cardId': 125,
    'path': 'items/gloomhaven/64-151/gh-125-curious-gear.png'
  },
  {
    'cardId': 126,
    'path': 'items/gloomhaven/64-151/gh-126-remote-spider.png'
  },
  {
    'cardId': 127,
    'path': 'items/gloomhaven/64-151/gh-127-giant-remote-spider.png'
  },
  {
    'cardId': 128,
    'path': 'items/gloomhaven/64-151/gh-128-black-censer.png'
  },
  {
    'cardId': 129,
    'path': 'items/gloomhaven/64-151/gh-129-black-card.png'
  },
  {
    'cardId': 130,
    'path': 'items/gloomhaven/64-151/gh-130-helix-ring.png'
  },
  {
    'cardId': 131,
    'path': 'items/gloomhaven/64-151/gh-131-heart-of-the-betrayer.png'
  },
  {
    'cardId': 132,
    'path': 'items/gloomhaven/64-151/gh-132-power-core.png'
  },
  {
    'cardId': 133,
    'path': 'items/gloomhaven/64-151/gh-133-resonant-crystal.png'
  },
  {
    'cardId': 134,
    'path': 'items/gloomhaven/64-151/gh-134-imposing-blade.png'
  },
  {
    'cardId': 135,
    'path': 'items/gloomhaven/64-151/gh-135-focusing-ray.png'
  },
  {
    'cardId': 136,
    'path': 'items/gloomhaven/64-151/gh-136-volatile-elixir.png'
  },
  {
    'cardId': 137,
    'path': 'items/gloomhaven/64-151/gh-137-silent-stiletto.png'
  },
  {
    'cardId': 138,
    'path': 'items/gloomhaven/64-151/gh-138-stone-charm.png'
  },
  {
    'cardId': 139,
    'path': 'items/gloomhaven/64-151/gh-139-psychic-knife.png'
  },
  {
    'cardId': 140,
    'path': 'items/gloomhaven/64-151/gh-140-sun-shield.png'
  },
  {
    'cardId': 141,
    'path': 'items/gloomhaven/64-151/gh-141-utility-belt.png'
  },
  {
    'cardId': 142,
    'path': 'items/gloomhaven/64-151/gh-142-phasing-idol.png'
  },
  {
    'cardId': 143,
    'path': 'items/gloomhaven/64-151/gh-143-smoke-elixir.png'
  },
  {
    'cardId': 144,
    'path': 'items/gloomhaven/64-151/gh-144-pendant-of-the-plague.png'
  },
  {
    'cardId': 145,
    'path': 'items/gloomhaven/64-151/gh-145-mask-of-death.png'
  },
  {
    'cardId': 146,
    'path': 'items/gloomhaven/64-151/gh-146-masters-lute.png'
  },
  {
    'cardId': 147,
    'path': 'items/gloomhaven/64-151/gh-147-cloak-of-the-hunter.png'
  },
  {
    'cardId': 148,
    'path': 'items/gloomhaven/64-151/gh-148-doctors-coat.png'
  },
  {
    'cardId': 149,
    'path': 'items/gloomhaven/64-151/gh-149-elemental-boots.png'
  },
  {
    'cardId': 150,
    'path': 'items/gloomhaven/64-151/gh-150-staff-of-command.png'
  },
  {
    'cardId': 151,
    'path': 'items/gloomhaven/64-151/gh-151-sword-of-the-sands.png'
  }
] as const;
export const gloomhavenItems = itemData.reduce((acc, cur) => acc.set(cur.cardId, cur.path), new Map<number, string>())
